version: '3.8'
services:
  axonserver:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - ./axonserver/data:/data
      - ./axonserver/events:/eventdata
