server:
  port: 8081

spring:
  application:
    name: order-command-service

axon:
  axonserver:
    servers: localhost:8124
  serializer:
    general: jackson
    messages: jackson
    events: jackson